name: basic checks

on: [pull_request, push]

jobs:

  check:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: verify debian changelog
      run: |
        VERSION=$(awk '/static const char version/ { gsub(/[\";]/, "", $6); print $6; exit }' ttyrec.c)
        if ! head -n1 debian/changelog | grep -F "ovh-ttyrec ($VERSION) master"; then
          echo "inconsistency between version ($VERSION) and debian changelog:"
          head -n1 debian/changelog
          exit 1
        fi

    - name: install prerequisites
      run: sudo apt-get install -y uncrustify make git debhelper

    - name: check style
      run: |
        ./configure
        make style
        git diff
        if ! git diff --quiet; then
          echo "Please make style."
          exit 1
        fi

    - name: compile with zstd autodetection (none)
      run: |
        make clean && ./configure && make -j$(nproc) && ./ttyrec -V
        if ./ttyrec -V | grep -qF 'zstd'; then
            exit 1
        fi

    - name: compile with zstd autodetection (static)
      run: |
        sudo apt-get install -y libzstd-dev
        make clean && ./configure && make -j$(nproc) && ./ttyrec -V
        ./ttyrec -V | grep -qF 'zstd[static]'

    - name: compile with shared libzstd
      run: |
        make clean && NO_STATIC_ZSTD=1 ./configure && make -j$(nproc) && ./ttyrec -V
        if ./ttyrec -V | grep -qF 'zstd[static]'; then
            exit 1
        fi
        ./ttyrec -V | grep -qF 'zstd'

    - name: compile without zstd support
      run: |
        make clean && NO_ZSTD=1 ./configure && make -j$(nproc) && ./ttyrec -V
        if ./ttyrec -V | grep -qF 'zstd'; then
            exit 1
        fi

    - name: build and test debian package
      run: |
        make clean && ./configure && make -j$(nproc) && ./ttyrec -V
        make deb
        ls -l ..
        sudo dpkg -i ../ovh-ttyrec_*.deb
        dpkg -L ovh-ttyrec
